default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("MYSQL_HOST") { 'localhost' } %>
  username: exercism_v3
  password: exercism_v3
  socket: /tmp/mysql.sock
  timeout: 5000
  variables:
    sql_mode: traditional

development:
  primary:
    <<: *default
    database: exercism_v3_development
  dj:
    <<: *default
    database: exercism_v3_dj_development
    migrations_paths: "db/dj_migrate"
test:
  primary:
    <<: *default
    database: exercism_v3_test
  dj:
    <<: *default
    database: exercism_v3_dj_test
    migrations_paths: "db/dj_migrate"
